<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('stock_opname_cycles', function(Blueprint $t){ $t->id(); $t->string('cycle_no',30)->unique(); $t->string('source_database',30); $t->date('cutoff_date'); $t->string('status',20)->default('DRAFT')->index(); $t->timestampTz('started_at')->nullable(); $t->timestampTz('completed_at')->nullable(); $t->timestampTz('closing_snapshot_at')->nullable(); $t->text('closing_snapshot_error')->nullable(); $t->foreignId('created_by')->constrained('users'); $t->timestamps(); });
Schema::create('cycle_warehouses', function(Blueprint $t){ $t->id(); $t->foreignId('cycle_id')->constrained('stock_opname_cycles')->cascadeOnDelete(); $t->bigInteger('erp_warehouse_id'); $t->string('warehouse_code',100); $t->string('warehouse_name'); $t->timestampTz('created_at')->useCurrent(); $t->unique(['cycle_id','erp_warehouse_id']); });
Schema::create('checker_assignments', function(Blueprint $t){ $t->id(); $t->foreignId('cycle_id')->constrained('stock_opname_cycles')->cascadeOnDelete(); $t->foreignId('warehouse_id')->constrained('cycle_warehouses')->cascadeOnDelete(); $t->foreignId('checker_id')->constrained('users'); $t->foreignId('assigned_by')->constrained('users'); $t->timestampTz('created_at')->useCurrent(); $t->unique(['cycle_id','warehouse_id','checker_id'],'checker_assignment_unique'); $t->index(['checker_id','cycle_id']); });
Schema::create('stock_snapshots', function(Blueprint $t){ $t->id(); $t->foreignId('cycle_id')->constrained('stock_opname_cycles')->cascadeOnDelete(); $t->foreignId('warehouse_id')->constrained('cycle_warehouses')->cascadeOnDelete(); $t->bigInteger('erp_warehouse_id'); $t->string('warehouse_code',100); $t->bigInteger('item_id'); $t->string('item_code',100); $t->string('item_name')->nullable(); $t->decimal('opening_system_qty',28,4)->default(0); $t->decimal('closing_system_qty',28,4)->nullable(); $t->timestampTz('opening_snapshot_at')->nullable(); $t->timestampTz('closing_snapshot_at')->nullable(); $t->unique(['cycle_id','warehouse_id','item_id'],'stock_snapshot_unique'); $t->index(['cycle_id','item_code']); });
Schema::create('scan_sessions', function(Blueprint $t){ $t->id(); $t->foreignId('cycle_id')->constrained('stock_opname_cycles')->cascadeOnDelete(); $t->foreignId('warehouse_id')->constrained('cycle_warehouses')->cascadeOnDelete(); $t->foreignId('checker_id')->constrained('users'); $t->string('location'); $t->timestampTz('started_at'); $t->timestampTz('ended_at')->nullable(); $t->index(['checker_id','cycle_id','ended_at']); });
Schema::create('scan_transactions', function(Blueprint $t){ $t->bigIncrements('id'); $t->foreignId('cycle_id')->constrained('stock_opname_cycles')->cascadeOnDelete(); $t->foreignId('scan_session_id')->constrained('scan_sessions')->cascadeOnDelete(); $t->foreignId('warehouse_id')->constrained('cycle_warehouses')->cascadeOnDelete(); $t->foreignId('checker_id')->constrained('users'); $t->string('location'); $t->string('alias_code',150)->index(); $t->bigInteger('item_id'); $t->string('item_code',100); $t->string('item_name')->nullable(); $t->unsignedTinyInteger('uom_level'); $t->string('uom_code',50); $t->decimal('ratio_used',28,4); $t->decimal('physical_qty',28,4); $t->timestampTz('scanned_at')->index(); $t->index(['cycle_id','warehouse_id','item_id']); $t->index(['cycle_id','checker_id']); });
} public function down(): void { Schema::dropIfExists('scan_transactions'); Schema::dropIfExists('scan_sessions'); Schema::dropIfExists('stock_snapshots'); Schema::dropIfExists('checker_assignments'); Schema::dropIfExists('cycle_warehouses'); Schema::dropIfExists('stock_opname_cycles'); } };
